// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9MHMGlaZkcaQolo0JxZ-3m9sM0tekClA',
    appId: '1:846699104254:web:02f9036834946abc83e2af',
    databaseURL: 'https://console.firebase.google.com/project/chatapp-a298f',
    messagingSenderId: '846699104254',
    projectId: 'chatapp-a298f',
    authDomain: 'chatapp-a298f.firebaseapp.com',
    storageBucket: 'chatapp-a298f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvPuJGiKWj-r1wmI2FZh2KCRsPq4dkVYk',
    appId: '1:846699104254:android:0c70ed0a2752664d83e2af',
    messagingSenderId: '846699104254',
    projectId: 'chatapp-a298f',
    storageBucket: 'chatapp-a298f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYJy3zFODP-WhQQ0GW7q5XyqTY_-q6Zak',
    appId: '1:846699104254:ios:a426f7d48cae227683e2af',
    messagingSenderId: '846699104254',
    projectId: 'chatapp-a298f',
    storageBucket: 'chatapp-a298f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYJy3zFODP-WhQQ0GW7q5XyqTY_-q6Zak',
    appId: '1:846699104254:ios:9332ba8d141bcda883e2af',
    messagingSenderId: '846699104254',
    projectId: 'chatapp-a298f',
    storageBucket: 'chatapp-a298f.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
